/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_18;

/**
 *
 * @author Juan Pablo
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfa
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        BTNCALCULAR = new javax.swing.JButton();
        LBLRETENCION = new javax.swing.JLabel();
        LBLTRABAJADOR = new javax.swing.JLabel();
        LBID = new javax.swing.JLabel();
        LBHORASTRABAJADAS = new javax.swing.JLabel();
        LBLCOSTO = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TXTRETENCION = new javax.swing.JTextField();
        TXTNOMBRE = new javax.swing.JTextField();
        TXTHORAS = new javax.swing.JTextField();
        TXTID = new javax.swing.JTextField();
        TXTCOSTO = new javax.swing.JTextField();
        TXTPRINT = new javax.swing.JTextArea();
        SALIR = new javax.swing.JButton();
        BORRAR = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNCALCULAR.setBackground(new java.awt.Color(255, 153, 153));
        BTNCALCULAR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNCALCULAR.setForeground(new java.awt.Color(0, 0, 0));
        BTNCALCULAR.setText("CALCULAR");
        BTNCALCULAR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTNCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULARActionPerformed(evt);
            }
        });
        fondo.add(BTNCALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, 50));

        LBLRETENCION.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LBLRETENCION.setForeground(new java.awt.Color(0, 0, 0));
        LBLRETENCION.setText("RETENCION DE LA FUENTE (%):");
        LBLRETENCION.setToolTipText("");
        fondo.add(LBLRETENCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        LBLTRABAJADOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LBLTRABAJADOR.setForeground(new java.awt.Color(0, 0, 0));
        LBLTRABAJADOR.setText("NOMBRE DEL TRABAJADOR:");
        LBLTRABAJADOR.setToolTipText("");
        fondo.add(LBLTRABAJADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        LBID.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LBID.setForeground(new java.awt.Color(0, 0, 0));
        LBID.setText("IDENTIFICACION TRABAJADOR:");
        LBID.setToolTipText("");
        fondo.add(LBID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        LBHORASTRABAJADAS.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LBHORASTRABAJADAS.setForeground(new java.awt.Color(0, 0, 0));
        LBHORASTRABAJADAS.setText("HORAS TRABAJADAS:");
        LBHORASTRABAJADAS.setToolTipText("");
        fondo.add(LBHORASTRABAJADAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        LBLCOSTO.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LBLCOSTO.setForeground(new java.awt.Color(0, 0, 0));
        LBLCOSTO.setText("COSTO POR HORA:");
        LBLCOSTO.setToolTipText("");
        fondo.add(LBLCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SALARIO BRUTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        TXTRETENCION.setBackground(new java.awt.Color(255, 153, 153));
        TXTRETENCION.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTRETENCION.setForeground(new java.awt.Color(0, 0, 0));
        TXTRETENCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRETENCIONActionPerformed(evt);
            }
        });
        fondo.add(TXTRETENCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 270, 30));

        TXTNOMBRE.setBackground(new java.awt.Color(255, 153, 153));
        TXTNOMBRE.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTNOMBRE.setForeground(new java.awt.Color(0, 0, 0));
        TXTNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBREActionPerformed(evt);
            }
        });
        fondo.add(TXTNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 270, 30));

        TXTHORAS.setBackground(new java.awt.Color(255, 153, 153));
        TXTHORAS.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTHORAS.setForeground(new java.awt.Color(0, 0, 0));
        TXTHORAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHORASActionPerformed(evt);
            }
        });
        fondo.add(TXTHORAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 330, 30));

        TXTID.setBackground(new java.awt.Color(255, 153, 153));
        TXTID.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTID.setForeground(new java.awt.Color(0, 0, 0));
        TXTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDActionPerformed(evt);
            }
        });
        fondo.add(TXTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 280, 30));

        TXTCOSTO.setBackground(new java.awt.Color(255, 153, 153));
        TXTCOSTO.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTCOSTO.setForeground(new java.awt.Color(0, 0, 0));
        TXTCOSTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCOSTOActionPerformed(evt);
            }
        });
        fondo.add(TXTCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 360, 30));

        TXTPRINT.setBackground(new java.awt.Color(255, 255, 255));
        TXTPRINT.setColumns(20);
        TXTPRINT.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTPRINT.setForeground(new java.awt.Color(0, 0, 0));
        TXTPRINT.setRows(5);
        fondo.add(TXTPRINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 510, 110));

        SALIR.setBackground(new java.awt.Color(255, 153, 153));
        SALIR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SALIR.setForeground(new java.awt.Color(0, 0, 0));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        fondo.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 50));

        BORRAR.setBackground(new java.awt.Color(255, 153, 153));
        BORRAR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BORRAR.setForeground(new java.awt.Color(0, 0, 0));
        BORRAR.setText("BORRAR");
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });
        fondo.add(BORRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 120, 50));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULARActionPerformed
        // TODO add your handling code here:
        String nombre = TXTNOMBRE.getText();
        String ID = TXTID.getText();
        double horas = Double.parseDouble(TXTHORAS.getText());
        double valorhora = Double.parseDouble(TXTCOSTO.getText());
        double impuesto = Double.parseDouble(TXTRETENCION.getText());
        
        SALARIO salario = new SALARIO();
        
        TXTPRINT.setText(salario.calcularsalario(ID, nombre, horas, valorhora, impuesto));
        
    }//GEN-LAST:event_BTNCALCULARActionPerformed

    private void TXTRETENCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRETENCIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRETENCIONActionPerformed

    private void TXTNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBREActionPerformed

    private void TXTHORASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHORASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTHORASActionPerformed

    private void TXTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDActionPerformed

    private void TXTCOSTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCOSTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCOSTOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
        // TODO add your handling code here:
        TXTCOSTO.setText("");
        TXTHORAS.setText("");
        TXTID.setText("");
        TXTNOMBRE.setText("");
        TXTPRINT.setText("");
        TXTRETENCION.setText("");
    }//GEN-LAST:event_BORRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton BTNCALCULAR;
    private javax.swing.JLabel LBHORASTRABAJADAS;
    private javax.swing.JLabel LBID;
    private javax.swing.JLabel LBLCOSTO;
    private javax.swing.JLabel LBLRETENCION;
    private javax.swing.JLabel LBLTRABAJADOR;
    private javax.swing.JButton SALIR;
    private javax.swing.JTextField TXTCOSTO;
    private javax.swing.JTextField TXTHORAS;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTNOMBRE;
    private javax.swing.JTextArea TXTPRINT;
    private javax.swing.JTextField TXTRETENCION;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
