/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_10;

/**
 *
 * @author Juan Pablo
 */
public class IU extends javax.swing.JFrame {

    /**
     * Creates new form IU
     */
    public IU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CALCULAR = new javax.swing.JButton();
        BTNBORRAR = new javax.swing.JButton();
        PATRIMONIO = new javax.swing.JTextField();
        NUMEROINSCRIPCION = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        ESTRATOSOCIAL = new javax.swing.JTextField();
        TXTPRINT = new javax.swing.JTextArea();
        SALIR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MATRICULA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 260, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DIGITE NUMERO INSCRIPCIÓN:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 40));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DIGITA TU NOMBRE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DIGITE DEL PATRIMONIO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 40));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DIGITE EL ESTRATO SOCIAL:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 40));

        CALCULAR.setBackground(new java.awt.Color(0, 102, 204));
        CALCULAR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        CALCULAR.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR.setText("CALCULAR");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, 40));

        BTNBORRAR.setBackground(new java.awt.Color(0, 102, 204));
        BTNBORRAR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNBORRAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNBORRAR.setText("BORRAR");
        BTNBORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBORRARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBORRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 120, 40));

        PATRIMONIO.setBackground(new java.awt.Color(255, 255, 204));
        PATRIMONIO.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(PATRIMONIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 230, 40));

        NUMEROINSCRIPCION.setBackground(new java.awt.Color(255, 255, 204));
        NUMEROINSCRIPCION.setForeground(new java.awt.Color(0, 0, 0));
        NUMEROINSCRIPCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMEROINSCRIPCIONActionPerformed(evt);
            }
        });
        jPanel1.add(NUMEROINSCRIPCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 40));

        NOMBRE.setBackground(new java.awt.Color(255, 255, 204));
        NOMBRE.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 260, 40));

        ESTRATOSOCIAL.setBackground(new java.awt.Color(255, 255, 204));
        ESTRATOSOCIAL.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ESTRATOSOCIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 210, 40));

        TXTPRINT.setColumns(20);
        TXTPRINT.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTPRINT.setRows(5);
        TXTPRINT.setWrapStyleWord(true);
        jPanel1.add(TXTPRINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 410, 90));

        SALIR1.setBackground(new java.awt.Color(0, 102, 204));
        SALIR1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        SALIR1.setForeground(new java.awt.Color(255, 255, 255));
        SALIR1.setText("SALIR");
        SALIR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIR1ActionPerformed(evt);
            }
        });
        jPanel1.add(SALIR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUMEROINSCRIPCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMEROINSCRIPCIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMEROINSCRIPCIONActionPerformed

    private void BTNBORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBORRARActionPerformed
        // TODO add your handling code here:
        NUMEROINSCRIPCION.setText("");
        NOMBRE.setText("");
        ESTRATOSOCIAL.setText("");
        PATRIMONIO.setText("");
        TXTPRINT.setText("");
    }//GEN-LAST:event_BTNBORRARActionPerformed

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        // TODO add your handling code here:

        String ni = NUMEROINSCRIPCION.getText();
        String nombre = NOMBRE.getText();
        double patrimonio = Double.parseDouble(PATRIMONIO.getText());
        int estrato = Integer.parseInt(ESTRATOSOCIAL.getText());

        MATRICULA matri = new MATRICULA();   

        TXTPRINT.setText(matri.calcular(ni, nombre, patrimonio, estrato));
    }//GEN-LAST:event_CALCULARActionPerformed

    private void SALIR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIR1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SALIR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBORRAR;
    private javax.swing.JButton CALCULAR;
    private javax.swing.JTextField ESTRATOSOCIAL;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField NUMEROINSCRIPCION;
    private javax.swing.JTextField PATRIMONIO;
    private javax.swing.JButton SALIR1;
    private javax.swing.JTextArea TXTPRINT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
