package figuras_geometricas;


import figuras_geometricas.Circulo;
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juan Pablo
 */
public class INTERFAZFIGURAS extends javax.swing.JFrame {
    
    
    public INTERFAZFIGURAS() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        FCIRCULO = new javax.swing.JLabel();
        TXTRADIO = new javax.swing.JTextField();
        RADIOCIRCULO = new javax.swing.JLabel();
        TLTCIRCULO = new javax.swing.JLabel();
        AREACIRCULO = new javax.swing.JLabel();
        AREACIRCULOR = new javax.swing.JTextField();
        PERIMETROCIRCULO = new javax.swing.JLabel();
        PERIMETROCIRCULOR = new javax.swing.JTextField();
        BTNCALCULAR1 = new javax.swing.JButton();
        BTNBORRAR1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        FRCUADRADO = new javax.swing.JLabel();
        LADOC = new javax.swing.JLabel();
        TLTCUADRADO = new javax.swing.JLabel();
        AREACUADRADO = new javax.swing.JLabel();
        AREACUADRADOR = new javax.swing.JTextField();
        PERIMETROCUADRADO = new javax.swing.JLabel();
        PERIMETROCUADRADOR = new javax.swing.JTextField();
        BTNCALCULAR2 = new javax.swing.JButton();
        BTNBORRAR2 = new javax.swing.JButton();
        TXTLADOC = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        FRRECTANGULO = new javax.swing.JLabel();
        TXTBASEREC = new javax.swing.JTextField();
        BASEREC = new javax.swing.JLabel();
        TLTRECTANGULO = new javax.swing.JLabel();
        AREARECTANGULO = new javax.swing.JLabel();
        AREARECTANGULOR = new javax.swing.JTextField();
        PERIMETRORECTANGULO = new javax.swing.JLabel();
        PERIMETRORECTANGULOR = new javax.swing.JTextField();
        BTNCALCULAR3 = new javax.swing.JButton();
        BTNBORRAR3 = new javax.swing.JButton();
        ALTURAREC = new javax.swing.JLabel();
        TXTALTURAREC = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        FRTRIANGULO = new javax.swing.JLabel();
        TXTBASET = new javax.swing.JTextField();
        BASET = new javax.swing.JLabel();
        TLTTRIANGULO = new javax.swing.JLabel();
        AREATRIANGULO = new javax.swing.JLabel();
        AREATRIANGULOR = new javax.swing.JTextField();
        PERIMETROTRIANGULO = new javax.swing.JLabel();
        PERIMETROTRIANGULOR = new javax.swing.JTextField();
        BTNBORRAR4 = new javax.swing.JButton();
        ALTURAT = new javax.swing.JLabel();
        TXTALTURAT = new javax.swing.JTextField();
        PERIMETROTRIANGULO1 = new javax.swing.JLabel();
        TIPOT = new javax.swing.JTextField();
        BTNCALCULAR5 = new javax.swing.JButton();
        BORRARTODO = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        TITULO.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("FIGURAS GEOMETRICAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FCIRCULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circulo_azul.png"))); // NOI18N
        jPanel3.add(FCIRCULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, -1));

        TXTRADIO.setBackground(new java.awt.Color(204, 204, 204));
        TXTRADIO.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTRADIO.setForeground(new java.awt.Color(0, 0, 0));
        TXTRADIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRADIOActionPerformed(evt);
            }
        });
        jPanel3.add(TXTRADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 90, 30));

        RADIOCIRCULO.setBackground(new java.awt.Color(0, 0, 0));
        RADIOCIRCULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        RADIOCIRCULO.setForeground(new java.awt.Color(0, 0, 0));
        RADIOCIRCULO.setText("RADIO:");
        jPanel3.add(RADIOCIRCULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 70, 50));

        TLTCIRCULO.setBackground(new java.awt.Color(0, 0, 0));
        TLTCIRCULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        TLTCIRCULO.setForeground(new java.awt.Color(0, 0, 0));
        TLTCIRCULO.setText("CIRCULO");
        jPanel3.add(TLTCIRCULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 50));

        AREACIRCULO.setBackground(new java.awt.Color(0, 0, 0));
        AREACIRCULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        AREACIRCULO.setForeground(new java.awt.Color(0, 0, 0));
        AREACIRCULO.setText("AREA:");
        jPanel3.add(AREACIRCULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 50));

        AREACIRCULOR.setBackground(new java.awt.Color(255, 255, 255));
        AREACIRCULOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        AREACIRCULOR.setBorder(null);
        AREACIRCULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREACIRCULORActionPerformed(evt);
            }
        });
        jPanel3.add(AREACIRCULOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 60, 40));

        PERIMETROCIRCULO.setBackground(new java.awt.Color(0, 0, 0));
        PERIMETROCIRCULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        PERIMETROCIRCULO.setForeground(new java.awt.Color(0, 0, 0));
        PERIMETROCIRCULO.setText("PERIMETRO:");
        jPanel3.add(PERIMETROCIRCULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 120, 50));

        PERIMETROCIRCULOR.setBackground(new java.awt.Color(255, 255, 255));
        PERIMETROCIRCULOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        PERIMETROCIRCULOR.setBorder(null);
        PERIMETROCIRCULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETROCIRCULORActionPerformed(evt);
            }
        });
        jPanel3.add(PERIMETROCIRCULOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 60, 40));

        BTNCALCULAR1.setBackground(new java.awt.Color(0, 0, 153));
        BTNCALCULAR1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNCALCULAR1.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR1.setText("CALCULAR");
        BTNCALCULAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULAR1ActionPerformed(evt);
            }
        });
        jPanel3.add(BTNCALCULAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));

        BTNBORRAR1.setBackground(new java.awt.Color(0, 0, 153));
        BTNBORRAR1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNBORRAR1.setForeground(new java.awt.Color(255, 255, 255));
        BTNBORRAR1.setText("BORRAR");
        BTNBORRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBORRAR1ActionPerformed(evt);
            }
        });
        jPanel3.add(BTNBORRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, 30));

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 90, 410, 290));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FRCUADRADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CUADRADO.png"))); // NOI18N
        jPanel4.add(FRCUADRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, -1));

        LADOC.setBackground(new java.awt.Color(0, 0, 0));
        LADOC.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        LADOC.setForeground(new java.awt.Color(0, 0, 0));
        LADOC.setText("LADO:");
        jPanel4.add(LADOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 80, 50));

        TLTCUADRADO.setBackground(new java.awt.Color(0, 0, 0));
        TLTCUADRADO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        TLTCUADRADO.setForeground(new java.awt.Color(0, 0, 0));
        TLTCUADRADO.setText("CUADRADO");
        jPanel4.add(TLTCUADRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 50));

        AREACUADRADO.setBackground(new java.awt.Color(0, 0, 0));
        AREACUADRADO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        AREACUADRADO.setForeground(new java.awt.Color(0, 0, 0));
        AREACUADRADO.setText("AREA:");
        jPanel4.add(AREACUADRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 50));

        AREACUADRADOR.setBackground(new java.awt.Color(255, 255, 255));
        AREACUADRADOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        AREACUADRADOR.setBorder(null);
        AREACUADRADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREACUADRADORActionPerformed(evt);
            }
        });
        jPanel4.add(AREACUADRADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 60, 40));

        PERIMETROCUADRADO.setBackground(new java.awt.Color(0, 0, 0));
        PERIMETROCUADRADO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        PERIMETROCUADRADO.setForeground(new java.awt.Color(0, 0, 0));
        PERIMETROCUADRADO.setText("PERIMETRO:");
        jPanel4.add(PERIMETROCUADRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 120, 50));

        PERIMETROCUADRADOR.setBackground(new java.awt.Color(255, 255, 255));
        PERIMETROCUADRADOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        PERIMETROCUADRADOR.setBorder(null);
        PERIMETROCUADRADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETROCUADRADORActionPerformed(evt);
            }
        });
        jPanel4.add(PERIMETROCUADRADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 60, 40));

        BTNCALCULAR2.setBackground(new java.awt.Color(0, 0, 153));
        BTNCALCULAR2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNCALCULAR2.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR2.setText("CALCULAR");
        BTNCALCULAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULAR2ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNCALCULAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));

        BTNBORRAR2.setBackground(new java.awt.Color(0, 0, 153));
        BTNBORRAR2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNBORRAR2.setForeground(new java.awt.Color(255, 255, 255));
        BTNBORRAR2.setText("BORRAR");
        BTNBORRAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBORRAR2ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNBORRAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, 30));

        TXTLADOC.setBackground(new java.awt.Color(204, 204, 204));
        TXTLADOC.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTLADOC.setForeground(new java.awt.Color(0, 0, 0));
        TXTLADOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLADOCActionPerformed(evt);
            }
        });
        jPanel4.add(TXTLADOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 60, 30));

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 390, 290));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FRRECTANGULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rectangulo.png"))); // NOI18N
        jPanel5.add(FRRECTANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, 130, 150));

        TXTBASEREC.setBackground(new java.awt.Color(204, 204, 204));
        TXTBASEREC.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTBASEREC.setForeground(new java.awt.Color(0, 0, 0));
        TXTBASEREC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBASERECActionPerformed(evt);
            }
        });
        jPanel5.add(TXTBASEREC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 30));

        BASEREC.setBackground(new java.awt.Color(0, 0, 0));
        BASEREC.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        BASEREC.setForeground(new java.awt.Color(0, 0, 0));
        BASEREC.setText("BASE:");
        jPanel5.add(BASEREC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 50));

        TLTRECTANGULO.setBackground(new java.awt.Color(0, 0, 0));
        TLTRECTANGULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        TLTRECTANGULO.setForeground(new java.awt.Color(0, 0, 0));
        TLTRECTANGULO.setText("RECTANGULO");
        jPanel5.add(TLTRECTANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 50));

        AREARECTANGULO.setBackground(new java.awt.Color(0, 0, 0));
        AREARECTANGULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        AREARECTANGULO.setForeground(new java.awt.Color(0, 0, 0));
        AREARECTANGULO.setText("AREA:");
        jPanel5.add(AREARECTANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, 50));

        AREARECTANGULOR.setBackground(new java.awt.Color(255, 255, 255));
        AREARECTANGULOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        AREARECTANGULOR.setBorder(null);
        AREARECTANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREARECTANGULORActionPerformed(evt);
            }
        });
        jPanel5.add(AREARECTANGULOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 40));

        PERIMETRORECTANGULO.setBackground(new java.awt.Color(0, 0, 0));
        PERIMETRORECTANGULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        PERIMETRORECTANGULO.setForeground(new java.awt.Color(0, 0, 0));
        PERIMETRORECTANGULO.setText("PERIMETRO:");
        jPanel5.add(PERIMETRORECTANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 50));

        PERIMETRORECTANGULOR.setBackground(new java.awt.Color(255, 255, 255));
        PERIMETRORECTANGULOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        PERIMETRORECTANGULOR.setBorder(null);
        PERIMETRORECTANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETRORECTANGULORActionPerformed(evt);
            }
        });
        jPanel5.add(PERIMETRORECTANGULOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 60, 40));

        BTNCALCULAR3.setBackground(new java.awt.Color(0, 0, 153));
        BTNCALCULAR3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNCALCULAR3.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR3.setText("CALCULAR");
        BTNCALCULAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULAR3ActionPerformed(evt);
            }
        });
        jPanel5.add(BTNCALCULAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));

        BTNBORRAR3.setBackground(new java.awt.Color(0, 0, 153));
        BTNBORRAR3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNBORRAR3.setForeground(new java.awt.Color(255, 255, 255));
        BTNBORRAR3.setText("BORRAR");
        BTNBORRAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBORRAR3ActionPerformed(evt);
            }
        });
        jPanel5.add(BTNBORRAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, 30));

        ALTURAREC.setBackground(new java.awt.Color(0, 0, 0));
        ALTURAREC.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        ALTURAREC.setForeground(new java.awt.Color(0, 0, 0));
        ALTURAREC.setText("ALTURA:");
        jPanel5.add(ALTURAREC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, 50));

        TXTALTURAREC.setBackground(new java.awt.Color(204, 204, 204));
        TXTALTURAREC.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTALTURAREC.setForeground(new java.awt.Color(0, 0, 0));
        TXTALTURAREC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTALTURARECActionPerformed(evt);
            }
        });
        jPanel5.add(TXTALTURAREC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 40, 30));

        background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 370, 410, 290));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FRTRIANGULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TRIANGULO.png"))); // NOI18N
        jPanel6.add(FRTRIANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 150));

        TXTBASET.setBackground(new java.awt.Color(204, 204, 204));
        TXTBASET.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTBASET.setForeground(new java.awt.Color(0, 0, 0));
        TXTBASET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBASETActionPerformed(evt);
            }
        });
        jPanel6.add(TXTBASET, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 30));

        BASET.setBackground(new java.awt.Color(0, 0, 0));
        BASET.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        BASET.setForeground(new java.awt.Color(0, 0, 0));
        BASET.setText("BASE:");
        jPanel6.add(BASET, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 50));

        TLTTRIANGULO.setBackground(new java.awt.Color(0, 0, 0));
        TLTTRIANGULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        TLTTRIANGULO.setForeground(new java.awt.Color(0, 0, 0));
        TLTTRIANGULO.setText("TRIANGULO");
        jPanel6.add(TLTTRIANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 50));

        AREATRIANGULO.setBackground(new java.awt.Color(0, 0, 0));
        AREATRIANGULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        AREATRIANGULO.setForeground(new java.awt.Color(0, 0, 0));
        AREATRIANGULO.setText("AREA:");
        jPanel6.add(AREATRIANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 60, 50));

        AREATRIANGULOR.setBackground(new java.awt.Color(255, 255, 255));
        AREATRIANGULOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        AREATRIANGULOR.setBorder(null);
        AREATRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREATRIANGULORActionPerformed(evt);
            }
        });
        jPanel6.add(AREATRIANGULOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 140, 40));

        PERIMETROTRIANGULO.setBackground(new java.awt.Color(0, 0, 0));
        PERIMETROTRIANGULO.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        PERIMETROTRIANGULO.setForeground(new java.awt.Color(0, 0, 0));
        PERIMETROTRIANGULO.setText("PERIMETRO:");
        jPanel6.add(PERIMETROTRIANGULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, 50));

        PERIMETROTRIANGULOR.setBackground(new java.awt.Color(255, 255, 255));
        PERIMETROTRIANGULOR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        PERIMETROTRIANGULOR.setBorder(null);
        PERIMETROTRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETROTRIANGULORActionPerformed(evt);
            }
        });
        jPanel6.add(PERIMETROTRIANGULOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 90, 40));

        BTNBORRAR4.setBackground(new java.awt.Color(0, 0, 153));
        BTNBORRAR4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNBORRAR4.setForeground(new java.awt.Color(255, 255, 255));
        BTNBORRAR4.setText("BORRAR");
        BTNBORRAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBORRAR4ActionPerformed(evt);
            }
        });
        jPanel6.add(BTNBORRAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 30));

        ALTURAT.setBackground(new java.awt.Color(0, 0, 0));
        ALTURAT.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        ALTURAT.setForeground(new java.awt.Color(0, 0, 0));
        ALTURAT.setText("ALTURA:");
        jPanel6.add(ALTURAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, 50));

        TXTALTURAT.setBackground(new java.awt.Color(204, 204, 204));
        TXTALTURAT.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TXTALTURAT.setForeground(new java.awt.Color(0, 0, 0));
        TXTALTURAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTALTURATActionPerformed(evt);
            }
        });
        jPanel6.add(TXTALTURAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 40, 30));

        PERIMETROTRIANGULO1.setBackground(new java.awt.Color(0, 0, 0));
        PERIMETROTRIANGULO1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        PERIMETROTRIANGULO1.setForeground(new java.awt.Color(0, 0, 0));
        PERIMETROTRIANGULO1.setText("TIPO TRIANGULO:");
        PERIMETROTRIANGULO1.setToolTipText("");
        jPanel6.add(PERIMETROTRIANGULO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 170, 70));

        TIPOT.setBackground(new java.awt.Color(255, 255, 255));
        TIPOT.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TIPOT.setBorder(null);
        TIPOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPOTActionPerformed(evt);
            }
        });
        jPanel6.add(TIPOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 210, 30));

        BTNCALCULAR5.setBackground(new java.awt.Color(0, 0, 153));
        BTNCALCULAR5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BTNCALCULAR5.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR5.setText("CALCULAR");
        BTNCALCULAR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULAR5ActionPerformed(evt);
            }
        });
        jPanel6.add(BTNCALCULAR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 30));

        background.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 390, 290));

        BORRARTODO.setBackground(new java.awt.Color(0, 0, 153));
        BORRARTODO.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        BORRARTODO.setForeground(new java.awt.Color(255, 255, 255));
        BORRARTODO.setText("BORRAR");
        BORRARTODO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARTODOActionPerformed(evt);
            }
        });
        background.add(BORRARTODO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, 110, 30));

        SALIR.setBackground(new java.awt.Color(0, 0, 153));
        SALIR.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        background.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, 110, 30));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBORRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBORRAR1ActionPerformed
        // TODO add your handling code here:
        TXTRADIO.setText("");
        AREACIRCULOR.setText("");
        PERIMETROCIRCULOR.setText("");
    }//GEN-LAST:event_BTNBORRAR1ActionPerformed

    private void TXTRADIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRADIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRADIOActionPerformed

    private void BTNCALCULAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULAR1ActionPerformed
        // TODO add your handling code here:
        
        int radio = Integer.parseInt(TXTRADIO.getText());
        
        Circulo circulo = new Circulo(radio);
        AREACIRCULOR.setText(String.valueOf(Math.round(circulo.calcularArea())));
        PERIMETROCIRCULOR.setText(String.valueOf(Math.round(circulo.calcularperimetro())));
        
        
    }//GEN-LAST:event_BTNCALCULAR1ActionPerformed

    private void PERIMETROCIRCULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETROCIRCULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETROCIRCULORActionPerformed

    private void AREACIRCULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREACIRCULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREACIRCULORActionPerformed

    private void AREACUADRADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREACUADRADORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREACUADRADORActionPerformed

    private void PERIMETROCUADRADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETROCUADRADORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETROCUADRADORActionPerformed

    private void BTNCALCULAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULAR2ActionPerformed
        // TODO add your handling code here:
        
        int ladoc = Integer.parseInt(TXTLADOC.getText());
        Cuadrado cuadrado = new Cuadrado(ladoc);
        
        AREACUADRADOR.setText(String.valueOf(cuadrado.CalcuarArea()));
        PERIMETROCUADRADOR.setText(String.valueOf(cuadrado.CalcularPerimetro()));
    }//GEN-LAST:event_BTNCALCULAR2ActionPerformed

    private void BTNBORRAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBORRAR2ActionPerformed
        // TODO add your handling code here:
        TXTLADOC.setText("");
        AREACUADRADOR.setText("");
        PERIMETROCUADRADOR.setText("");
                                                   
    }//GEN-LAST:event_BTNBORRAR2ActionPerformed

    private void TXTBASERECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBASERECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBASERECActionPerformed

    private void AREARECTANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREARECTANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREARECTANGULORActionPerformed

    private void PERIMETRORECTANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETRORECTANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETRORECTANGULORActionPerformed

    private void BTNCALCULAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULAR3ActionPerformed
        // RECTANGULO:
        
        int altura = Integer.parseInt(TXTALTURAREC.getText());
        int base = Integer.parseInt(TXTBASEREC.getText());
        
        Rectangulo rectangulo = new Rectangulo(base, altura);
        
        AREARECTANGULOR.setText(String.valueOf(rectangulo.area()));
        PERIMETRORECTANGULOR.setText(String.valueOf(rectangulo.perimetro()));
        
        
    }//GEN-LAST:event_BTNCALCULAR3ActionPerformed

    private void BTNBORRAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBORRAR3ActionPerformed
        // TODO add your handling code here:
        TXTBASEREC.setText("");
        TXTALTURAREC.setText("");
        AREARECTANGULOR.setText("");
        PERIMETRORECTANGULOR.setText("");
    }//GEN-LAST:event_BTNBORRAR3ActionPerformed

    private void TXTALTURARECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTALTURARECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTALTURARECActionPerformed

    private void TXTBASETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBASETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBASETActionPerformed

    private void AREATRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREATRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREATRIANGULORActionPerformed

    private void PERIMETROTRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETROTRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETROTRIANGULORActionPerformed

    private void BTNBORRAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBORRAR4ActionPerformed
        // TODO add your handling code here:
        AREATRIANGULOR.setText("");
        PERIMETROTRIANGULOR.setText("");
        TXTBASET.setText("");
        TXTALTURAT.setText("");
        
    }//GEN-LAST:event_BTNBORRAR4ActionPerformed

    private void TXTALTURATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTALTURATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTALTURATActionPerformed

    private void TIPOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPOTActionPerformed

    private void TXTLADOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLADOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLADOCActionPerformed

    private void BTNCALCULAR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULAR5ActionPerformed
        // TODO add your handling code here:
        
        int baset = Integer.parseInt(TXTBASET.getText());
        int alturat = Integer.parseInt(TXTALTURAT.getText());
        
        Triangulo_Rectangulo triangulo = new Triangulo_Rectangulo(baset, alturat);
        DecimalFormat df = new DecimalFormat("#.000");
        
        AREATRIANGULOR.setText(String.valueOf(df.format(triangulo.calcularArea())));
        PERIMETROTRIANGULOR.setText(String.valueOf(df.format(triangulo.calcularPerimetro())));
        TIPOT.setText(triangulo.determinarTipoTriangulo());
        
    }//GEN-LAST:event_BTNCALCULAR5ActionPerformed

    private void BORRARTODOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARTODOActionPerformed
        // TODO add your handling code here:
        
        TXTRADIO.setText("");
        AREACIRCULOR.setText("");
        PERIMETROCIRCULOR.setText("");
        
        TXTLADOC.setText("");
        AREACUADRADOR.setText("");
        PERIMETROCUADRADOR.setText("");
        
        TXTBASEREC.setText("");
        TXTALTURAREC.setText("");
        AREARECTANGULOR.setText("");
        PERIMETRORECTANGULOR.setText("");
        
        AREATRIANGULOR.setText("");
        PERIMETROTRIANGULOR.setText("");
        TXTBASET.setText("");
        TXTALTURAT.setText("");
        
    }//GEN-LAST:event_BORRARTODOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFAZFIGURAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFAZFIGURAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFAZFIGURAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFAZFIGURAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFAZFIGURAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALTURAREC;
    private javax.swing.JLabel ALTURAT;
    private javax.swing.JLabel AREACIRCULO;
    private javax.swing.JTextField AREACIRCULOR;
    private javax.swing.JLabel AREACUADRADO;
    private javax.swing.JTextField AREACUADRADOR;
    private javax.swing.JLabel AREARECTANGULO;
    private javax.swing.JTextField AREARECTANGULOR;
    private javax.swing.JLabel AREATRIANGULO;
    private javax.swing.JTextField AREATRIANGULOR;
    private javax.swing.JLabel BASEREC;
    private javax.swing.JLabel BASET;
    private javax.swing.JButton BORRARTODO;
    private javax.swing.JButton BTNBORRAR1;
    private javax.swing.JButton BTNBORRAR2;
    private javax.swing.JButton BTNBORRAR3;
    private javax.swing.JButton BTNBORRAR4;
    private javax.swing.JButton BTNCALCULAR1;
    private javax.swing.JButton BTNCALCULAR2;
    private javax.swing.JButton BTNCALCULAR3;
    private javax.swing.JButton BTNCALCULAR5;
    private javax.swing.JLabel FCIRCULO;
    private javax.swing.JLabel FRCUADRADO;
    private javax.swing.JLabel FRRECTANGULO;
    private javax.swing.JLabel FRTRIANGULO;
    private javax.swing.JLabel LADOC;
    private javax.swing.JLabel PERIMETROCIRCULO;
    private javax.swing.JTextField PERIMETROCIRCULOR;
    private javax.swing.JLabel PERIMETROCUADRADO;
    private javax.swing.JTextField PERIMETROCUADRADOR;
    private javax.swing.JLabel PERIMETRORECTANGULO;
    private javax.swing.JTextField PERIMETRORECTANGULOR;
    private javax.swing.JLabel PERIMETROTRIANGULO;
    private javax.swing.JLabel PERIMETROTRIANGULO1;
    private javax.swing.JTextField PERIMETROTRIANGULOR;
    private javax.swing.JLabel RADIOCIRCULO;
    private javax.swing.JButton SALIR;
    private javax.swing.JTextField TIPOT;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel TLTCIRCULO;
    private javax.swing.JLabel TLTCUADRADO;
    private javax.swing.JLabel TLTRECTANGULO;
    private javax.swing.JLabel TLTTRIANGULO;
    private javax.swing.JTextField TXTALTURAREC;
    private javax.swing.JTextField TXTALTURAT;
    private javax.swing.JTextField TXTBASEREC;
    private javax.swing.JTextField TXTBASET;
    private javax.swing.JTextField TXTLADOC;
    private javax.swing.JTextField TXTRADIO;
    private javax.swing.JPanel background;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
